// Copyright 2023 David A. (@dav991)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define OLED_DISPLAY_128X32
#define OLED_SCROLL_TIMEOUT 10000
#define OLED_TIMEOUT 60000
#define OLED_BRIGHTNESS 64
#define OLED_FADE_OUT
#define OLED_FADE_OUT_INTERVAL 10
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP26
#define I2C1_SCL_PIN GP27
#ifdef RGBLIGHT_ENABLE
#define RGBLIGHT_TIMEOUT 600
#define RGBLIGHT_LIMIT_VAL 120
#define RGBLIGHT_HUE_STEP 2
#define RGBLIGHT_SAT_STEP 5
#define RGBLIGHT_VAL_STEP 5
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING+0
#define WS2812_PIO_USE_PIO1
#define WS2812_DI_PIN GP28
#define RGBLED_NUM 72
#define RGBLIGHT_SLEEP
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
#endif // RGBLIGHT_ENABLE

#define DEBOUNCE 10